name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Grant gradlew execute permission
        run: chmod +x gradlew

      - name: Install Google Chrome (latest stable)
        run: |
          wget -q -O google-chrome-stable_current_amd64.deb \
               https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Setup matching ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      - name: Run tests
        run: ./gradlew test
